local Trials_Gold_enemy = 
{
	["21001"] = 
	{
		["acp"] = [[40]],
		["acp_upgrade"] = [[4]],
		["atk"] = [[220]],
		["atk_upgrade"] = [[22]],
		["blood"] = [[0]],
		["blood_upgrade"] = [[0]],
		["body_box"] = {
			[[0]],
			[[0]],
			[[96]],
			[[280]]
		},
		["break_upgrade"] = [[10]],
		["breaks"] = [[500]],
		["crit"] = [[40]],
		["crit_upgrade"] = [[4]],
		["defense"] = [[200]],
		["defense_upgrade"] = [[4]],
		["dodge"] = [[1]],
		["dodge_upgrade"] = [[1]],
		["hp"] = [[8000]],
		["hp_upgrade"] = [[1000]],
		["id"] = [[21001]],
		["image"] = [[Clock1]],
		["info"] = [[0]],
		["m_acp"] = [[40]],
		["m_acp_upgrade"] = [[4]],
		["m_atk"] = [[220]],
		["m_atk_upgrade"] = [[22]],
		["m_defense"] = [[200]],
		["m_defense_upgrade"] = [[4]],
		["name"] = [[物理小]],
		["rate"] = [[80]],
		["rate_upgrade"] = [[8]],
		["tumble"] = [[500]],
		["tumble_upgrade"] = [[10]],
		["type"] = [[1]]
	},
	["21002"] = 
	{
		["acp"] = [[40]],
		["acp_upgrade"] = [[4]],
		["atk"] = [[220]],
		["atk_upgrade"] = [[22]],
		["blood"] = [[0]],
		["blood_upgrade"] = [[0]],
		["body_box"] = {
			[[0]],
			[[0]],
			[[96]],
			[[280]]
		},
		["break_upgrade"] = [[10]],
		["breaks"] = [[500]],
		["crit"] = [[40]],
		["crit_upgrade"] = [[4]],
		["defense"] = [[200]],
		["defense_upgrade"] = [[4]],
		["dodge"] = [[1]],
		["dodge_upgrade"] = [[1]],
		["hp"] = [[16000]],
		["hp_upgrade"] = [[2000]],
		["id"] = [[21002]],
		["image"] = [[Clock2]],
		["info"] = [[0]],
		["m_acp"] = [[40]],
		["m_acp_upgrade"] = [[4]],
		["m_atk"] = [[220]],
		["m_atk_upgrade"] = [[22]],
		["m_defense"] = [[200]],
		["m_defense_upgrade"] = [[4]],
		["name"] = [[物理中]],
		["rate"] = [[80]],
		["rate_upgrade"] = [[8]],
		["tumble"] = [[500]],
		["tumble_upgrade"] = [[10]],
		["type"] = [[2]]
	},
	["21003"] = 
	{
		["acp"] = [[40]],
		["acp_upgrade"] = [[4]],
		["atk"] = [[220]],
		["atk_upgrade"] = [[22]],
		["blood"] = [[0]],
		["blood_upgrade"] = [[0]],
		["body_box"] = {
			[[0]],
			[[0]],
			[[96]],
			[[280]]
		},
		["break_upgrade"] = [[10]],
		["breaks"] = [[500]],
		["crit"] = [[40]],
		["crit_upgrade"] = [[4]],
		["defense"] = [[200]],
		["defense_upgrade"] = [[4]],
		["dodge"] = [[1]],
		["dodge_upgrade"] = [[1]],
		["hp"] = [[32000]],
		["hp_upgrade"] = [[4000]],
		["id"] = [[21003]],
		["image"] = [[Clock3]],
		["info"] = [[0]],
		["m_acp"] = [[40]],
		["m_acp_upgrade"] = [[4]],
		["m_atk"] = [[220]],
		["m_atk_upgrade"] = [[22]],
		["m_defense"] = [[200]],
		["m_defense_upgrade"] = [[4]],
		["name"] = [[物理大]],
		["rate"] = [[80]],
		["rate_upgrade"] = [[8]],
		["tumble"] = [[500]],
		["tumble_upgrade"] = [[10]],
		["type"] = [[3]]
	},
	["21004"] = 
	{
		["acp"] = [[40]],
		["acp_upgrade"] = [[4]],
		["atk"] = [[220]],
		["atk_upgrade"] = [[22]],
		["blood"] = [[0]],
		["blood_upgrade"] = [[0]],
		["body_box"] = {
			[[0]],
			[[0]],
			[[96]],
			[[280]]
		},
		["break_upgrade"] = [[10]],
		["breaks"] = [[500]],
		["crit"] = [[40]],
		["crit_upgrade"] = [[4]],
		["defense"] = [[200]],
		["defense_upgrade"] = [[4]],
		["dodge"] = [[1]],
		["dodge_upgrade"] = [[1]],
		["hp"] = [[8000]],
		["hp_upgrade"] = [[1000]],
		["id"] = [[21004]],
		["image"] = [[Clock4]],
		["info"] = [[0]],
		["m_acp"] = [[40]],
		["m_acp_upgrade"] = [[4]],
		["m_atk"] = [[220]],
		["m_atk_upgrade"] = [[22]],
		["m_defense"] = [[200]],
		["m_defense_upgrade"] = [[4]],
		["name"] = [[魔法小]],
		["rate"] = [[80]],
		["rate_upgrade"] = [[8]],
		["tumble"] = [[500]],
		["tumble_upgrade"] = [[10]],
		["type"] = [[4]]
	},
	["21005"] = 
	{
		["acp"] = [[40]],
		["acp_upgrade"] = [[4]],
		["atk"] = [[220]],
		["atk_upgrade"] = [[22]],
		["blood"] = [[0]],
		["blood_upgrade"] = [[0]],
		["body_box"] = {
			[[0]],
			[[0]],
			[[96]],
			[[280]]
		},
		["break_upgrade"] = [[10]],
		["breaks"] = [[500]],
		["crit"] = [[40]],
		["crit_upgrade"] = [[4]],
		["defense"] = [[200]],
		["defense_upgrade"] = [[4]],
		["dodge"] = [[1]],
		["dodge_upgrade"] = [[1]],
		["hp"] = [[16000]],
		["hp_upgrade"] = [[2000]],
		["id"] = [[21005]],
		["image"] = [[Clock5]],
		["info"] = [[0]],
		["m_acp"] = [[40]],
		["m_acp_upgrade"] = [[4]],
		["m_atk"] = [[220]],
		["m_atk_upgrade"] = [[22]],
		["m_defense"] = [[200]],
		["m_defense_upgrade"] = [[4]],
		["name"] = [[魔法中]],
		["rate"] = [[80]],
		["rate_upgrade"] = [[8]],
		["tumble"] = [[500]],
		["tumble_upgrade"] = [[10]],
		["type"] = [[5]]
	},
	["21006"] = 
	{
		["acp"] = [[40]],
		["acp_upgrade"] = [[4]],
		["atk"] = [[220]],
		["atk_upgrade"] = [[22]],
		["blood"] = [[0]],
		["blood_upgrade"] = [[0]],
		["body_box"] = {
			[[0]],
			[[0]],
			[[96]],
			[[280]]
		},
		["break_upgrade"] = [[10]],
		["breaks"] = [[500]],
		["crit"] = [[40]],
		["crit_upgrade"] = [[4]],
		["defense"] = [[200]],
		["defense_upgrade"] = [[4]],
		["dodge"] = [[1]],
		["dodge_upgrade"] = [[1]],
		["hp"] = [[32000]],
		["hp_upgrade"] = [[4000]],
		["id"] = [[21006]],
		["image"] = [[Clock6]],
		["info"] = [[0]],
		["m_acp"] = [[40]],
		["m_acp_upgrade"] = [[4]],
		["m_atk"] = [[220]],
		["m_atk_upgrade"] = [[22]],
		["m_defense"] = [[200]],
		["m_defense_upgrade"] = [[4]],
		["name"] = [[魔法大]],
		["rate"] = [[80]],
		["rate_upgrade"] = [[8]],
		["tumble"] = [[500]],
		["tumble_upgrade"] = [[10]],
		["type"] = [[6]]
	}
}
return Trials_Gold_enemy