require("config")
require("framework.init")

require("app.ui.base.init")
require("app.views.alert.init")
require("app.config.LoadConfig")
require("app.battle.BattleSound")

require("app.util.Common")
require("app.util.AudioManage")
require("app.util.GameDisplay")
require("app.util.CommonButton")
require("app.util.CommonView")
require("app.util.CommonSound")
require("app.util.ResManage")
require("app.util.Formula")

require("app.data.UIData")
require("app.data.GameExp")
require("app.data.TextData")
require("app.data.GamePoint")
require("app.data.StoreData")
require("app.data.GamePoint")
require("app.data.PlayerData")
require("app.data.HeroAbility")
require("app.data.ActivityUtil")
require("app.data.GameConstant")
require("app.data.EventConstant")

require("app.net.NetHandler")
require("app.net.ResponseEvent")
require("app.net.request.OperationCode")

ui = require("framework.ui")
cc.net = require("framework.cc.net.init")

display.DEFAULT_TTF_FONT = "FZY3JW--GB1-0.ttf"

cc.FileUtils:getInstance():addSearchPath("res/")
cc.FileUtils:getInstance():addSearchPath("res/json")
cc.FileUtils:getInstance():addSearchPath("res/fonts")
cc.FileUtils:getInstance():addSearchPath("res/map")
cc.FileUtils:getInstance():addSearchPath("res/missile")
cc.FileUtils:getInstance():addSearchPath("res/music")
cc.FileUtils:getInstance():addSearchPath("res/sound")
cc.FileUtils:getInstance():addSearchPath("res/sound/hero")
cc.FileUtils:getInstance():addSearchPath("res/sound/battle")
cc.FileUtils:getInstance():addSearchPath("res/sound/ui")

cc.FileUtils:getInstance():addSearchPath("res/icon")
cc.FileUtils:getInstance():addSearchPath("res/icon/hero_icon")
cc.FileUtils:getInstance():addSearchPath("res/icon/item_icon")
cc.FileUtils:getInstance():addSearchPath("res/icon/skill_icon")
cc.FileUtils:getInstance():addSearchPath("res/icon/stage_icon")
cc.FileUtils:getInstance():addSearchPath("res/icon/tails_icon")
cc.FileUtils:getInstance():addSearchPath("res/icon/union_icon")
cc.FileUtils:getInstance():addSearchPath("res/icon/skill_name_icon")

cc.FileUtils:getInstance():addSearchPath("res/gaf")
cc.FileUtils:getInstance():addSearchPath("res/gaf/door")
cc.FileUtils:getInstance():addSearchPath("res/gaf/character")
cc.FileUtils:getInstance():addSearchPath("res/gaf/enemy")
cc.FileUtils:getInstance():addSearchPath("res/gaf/buff")
cc.FileUtils:getInstance():addSearchPath("res/gaf/skill")
cc.FileUtils:getInstance():addSearchPath("res/gaf/enter")
cc.FileUtils:getInstance():addSearchPath("res/gaf/effect")
cc.FileUtils:getInstance():addSearchPath("res/gaf/tail")
cc.FileUtils:getInstance():addSearchPath("res/gaf/pet")
cc.FileUtils:getInstance():addSearchPath("res/gaf/clock")
cc.FileUtils:getInstance():addSearchPath("res/gaf/tower")
cc.FileUtils:getInstance():addSearchPath("res/gaf/ui")

cc.FileUtils:getInstance():addSearchPath("res/animation/tap")
cc.FileUtils:getInstance():addSearchPath("res/animation/card")
cc.FileUtils:getInstance():addSearchPath("res/animation/coin")
cc.FileUtils:getInstance():addSearchPath("res/animation/equip")
cc.FileUtils:getInstance():addSearchPath("res/animation/loading")
cc.FileUtils:getInstance():addSearchPath("res/animation/star_up")
cc.FileUtils:getInstance():addSearchPath("res/animation/level_up")
cc.FileUtils:getInstance():addSearchPath("res/animation/btn_skill")
cc.FileUtils:getInstance():addSearchPath("res/animation/btn_normal")
cc.FileUtils:getInstance():addSearchPath("res/animation/btn_activity")
cc.FileUtils:getInstance():addSearchPath("res/animation/wealth_btn")
cc.FileUtils:getInstance():addSearchPath("res/animation/wealth_ring")
cc.FileUtils:getInstance():addSearchPath("res/animation/wealth_star")
cc.FileUtils:getInstance():addSearchPath("res/animation/tiger_ring")
cc.FileUtils:getInstance():addSearchPath("res/animation/box_pay")
cc.FileUtils:getInstance():addSearchPath("res/animation/flip_ring")
cc.FileUtils:getInstance():addSearchPath("res/animation/flip_list1")
cc.FileUtils:getInstance():addSearchPath("res/animation/flip_list2")
cc.FileUtils:getInstance():addSearchPath("res/animation/flip_list3")

cc.FileUtils:getInstance():addSearchPath("res/images")
cc.FileUtils:getInstance():addSearchPath("res/images/backpack")
cc.FileUtils:getInstance():addSearchPath("res/images/hero_awake")
cc.FileUtils:getInstance():addSearchPath("res/images/hero_box")
cc.FileUtils:getInstance():addSearchPath("res/images/hero_get")
cc.FileUtils:getInstance():addSearchPath("res/images/hero_show")
cc.FileUtils:getInstance():addSearchPath("res/images/hero_system")
cc.FileUtils:getInstance():addSearchPath("res/images/item_use")
cc.FileUtils:getInstance():addSearchPath("res/images/turorial")
cc.FileUtils:getInstance():addSearchPath("res/images/account")
cc.FileUtils:getInstance():addSearchPath("res/images/common")
cc.FileUtils:getInstance():addSearchPath("res/images/chat")
cc.FileUtils:getInstance():addSearchPath("res/images/coin_box")
cc.FileUtils:getInstance():addSearchPath("res/images/drop_way")
cc.FileUtils:getInstance():addSearchPath("res/images/Shop")
cc.FileUtils:getInstance():addSearchPath("res/images/Stage")
cc.FileUtils:getInstance():addSearchPath("res/images/Bag")
cc.FileUtils:getInstance():addSearchPath("res/images/arena")
cc.FileUtils:getInstance():addSearchPath("res/images/Exchange")
cc.FileUtils:getInstance():addSearchPath("res/images/recharge")
cc.FileUtils:getInstance():addSearchPath("res/images/Ready")
cc.FileUtils:getInstance():addSearchPath("res/images/Login")
cc.FileUtils:getInstance():addSearchPath("res/images/Loading")
cc.FileUtils:getInstance():addSearchPath("res/images/background")
cc.FileUtils:getInstance():addSearchPath("res/images/trials")
cc.FileUtils:getInstance():addSearchPath("res/images/Tails")
cc.FileUtils:getInstance():addSearchPath("res/images/PlayerSet")
cc.FileUtils:getInstance():addSearchPath("res/images/Sweep")
cc.FileUtils:getInstance():addSearchPath("res/images/Mail")
cc.FileUtils:getInstance():addSearchPath("res/images/Quest")
cc.FileUtils:getInstance():addSearchPath("res/images/Register")
cc.FileUtils:getInstance():addSearchPath("res/images/Comic")
cc.FileUtils:getInstance():addSearchPath("res/images/Activity")
cc.FileUtils:getInstance():addSearchPath("res/images/Aincrad")
cc.FileUtils:getInstance():addSearchPath("res/images/font")
cc.FileUtils:getInstance():addSearchPath("res/images/battle")
cc.FileUtils:getInstance():addSearchPath("res/images/banner")
cc.FileUtils:getInstance():addSearchPath("res/images/word")
cc.FileUtils:getInstance():addSearchPath("res/images/Castle")
cc.FileUtils:getInstance():addSearchPath("res/images/Plot")
cc.FileUtils:getInstance():addSearchPath("res/images/Wanted")
cc.FileUtils:getInstance():addSearchPath("res/images/hero_flash")
cc.FileUtils:getInstance():addSearchPath("res/images/hero_card")
cc.FileUtils:getInstance():addSearchPath("res/images/ranking")
cc.FileUtils:getInstance():addSearchPath("res/images/summon")
cc.FileUtils:getInstance():addSearchPath("res/images/frame")
cc.FileUtils:getInstance():addSearchPath("res/images/discount_shop")
cc.FileUtils:getInstance():addSearchPath("res/images/union")
cc.FileUtils:getInstance():addSearchPath("res/images/union_battle")
cc.FileUtils:getInstance():addSearchPath("res/images/tiger")
cc.FileUtils:getInstance():addSearchPath("res/images/flip_fun")
cc.FileUtils:getInstance():addSearchPath("res/images/wealth")
cc.FileUtils:getInstance():addSearchPath("res/images/backfeed")
cc.FileUtils:getInstance():addSearchPath("res/images/equip")
cc.FileUtils:getInstance():addSearchPath("res/images/coin")
